import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

const REPO_README_TEMPLATE = (title, description, milestones) => `# ${title}

## SoulBridge Foundation — Ripple Grant Proposal

${description}

---

## 📋 Proposal Overview

| Field | Detail |
|-------|--------|
| **Project** | ${title} |
| **Program** | Ripple XRPL Grants |
| **Status** | Drafting |

---

## 🎯 Milestones

${milestones && milestones.length > 0 
  ? milestones.map((m, i) => `### Milestone ${i + 1}: ${m.title || 'TBD'}
- **Description:** ${m.description || 'TBD'}
- **Target Date:** ${m.target_date || 'TBD'}
- **Deliverables:** ${m.deliverables || 'TBD'}
- **Budget:** $${m.budget_usd || 'TBD'}
`).join('\n')
  : '> Milestones to be defined.\n'}

---

## 📁 Repository Structure

\`\`\`
├── README.md              # This file
├── proposal/              # Grant proposal documents
│   ├── proposal.md        # Main proposal document
│   ├── budget.md          # Detailed budget breakdown
│   └── team.md            # Team qualifications
├── milestones/            # Milestone deliverables
│   ├── milestone-1/
│   ├── milestone-2/
│   └── ...
├── reports/               # Progress reports
│   ├── monthly/
│   └── final/
└── assets/                # Supporting assets
\`\`\`

---

## 🏛️ SoulBridge Village

This grant proposal is managed by the SoulBridge Foundation through the SoulBridge Village platform.

- **Governance:** Aligned with the 11 Laws of SoulBridge
- **Transparency:** All progress tracked via GitHub issues and milestones
- **Accountability:** Constitutional multi-sig treasury management on XRPL

---

*Generated by SoulBridge Village — Law 2 (Honour) • Law 9 (Growth)*
`;

const PROPOSAL_TEMPLATE = `# Grant Proposal: [Title]

## Executive Summary
[Brief overview of what this project aims to achieve]

## Problem Statement
[What problem does this solve in the XRPL ecosystem?]

## Proposed Solution
[Detailed description of the solution]

## Technical Architecture
[Technical details and architecture overview]

## Use of XRPL
[How does this project leverage the XRP Ledger?]

## Team
[Team members and their qualifications]

## Budget
[Detailed budget breakdown]

## Timeline
[Project timeline with milestones]

## Success Metrics
[How will success be measured?]

## Risks and Mitigations
[Identified risks and mitigation strategies]
`;

const BUDGET_TEMPLATE = `# Budget Breakdown

## Overview
| Category | Amount (USD) | Percentage |
|----------|-------------|------------|
| Development | $ | % |
| Research | $ | % |
| Infrastructure | $ | % |
| Marketing | $ | % |
| Operations | $ | % |
| **Total** | **$** | **100%** |

## Detailed Line Items
[Itemized budget details]

## Payment Schedule
[How funds will be disbursed across milestones]
`;

const TEAM_TEMPLATE = `# Team

## Core Team

### [Name] — [Role]
- **Background:** 
- **Relevant Experience:** 
- **GitHub:** 

## Advisors

## SoulBridge Village Contributors
`;

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();

  if (!user || user.role !== 'admin') {
    return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
  }

  const body = await req.json();
  const { grant_proposal_id, org_name } = body;

  if (!grant_proposal_id) {
    return Response.json({ error: 'grant_proposal_id is required' }, { status: 400 });
  }

  // Fetch the grant proposal
  const proposal = await base44.asServiceRole.entities.GrantProposal.get(grant_proposal_id);
  if (!proposal) {
    return Response.json({ error: 'Grant proposal not found' }, { status: 404 });
  }

  // Check if repo already exists
  if (proposal.github_repo_url) {
    return Response.json({ 
      error: 'Repository already exists for this proposal',
      github_repo_url: proposal.github_repo_url 
    }, { status: 409 });
  }

  // Get GitHub access token
  const { accessToken } = await base44.asServiceRole.connectors.getConnection("github");

  // Generate repo name from title
  const repoName = 'grant-' + (proposal.title || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);

  // Create the repository
  const createRepoUrl = org_name 
    ? `https://api.github.com/orgs/${org_name}/repos`
    : 'https://api.github.com/user/repos';

  const repoRes = await fetch(createRepoUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      description: `SoulBridge Ripple Grant Proposal: ${proposal.title}`,
      private: true,
      has_issues: true,
      has_projects: true,
      auto_init: false,
    }),
  });

  if (!repoRes.ok) {
    const err = await repoRes.json();
    return Response.json({ error: 'Failed to create repository', details: err }, { status: repoRes.status });
  }

  const repo = await repoRes.json();

  // Create README.md
  const readmeContent = REPO_README_TEMPLATE(proposal.title, proposal.description, proposal.milestones);
  await createFile(accessToken, repo.full_name, 'README.md', readmeContent, 'Initial grant proposal structure');

  // Create proposal template files
  await createFile(accessToken, repo.full_name, 'proposal/proposal.md', PROPOSAL_TEMPLATE, 'Add proposal template');
  await createFile(accessToken, repo.full_name, 'proposal/budget.md', BUDGET_TEMPLATE, 'Add budget template');
  await createFile(accessToken, repo.full_name, 'proposal/team.md', TEAM_TEMPLATE, 'Add team template');

  // Create placeholder directories via .gitkeep
  const dirs = ['milestones/milestone-1', 'milestones/milestone-2', 'reports/monthly', 'reports/final', 'assets'];
  for (const dir of dirs) {
    await createFile(accessToken, repo.full_name, `${dir}/.gitkeep`, '', `Create ${dir} directory`);
  }

  // Create GitHub issues for milestones
  const milestoneIssues = [];
  if (proposal.milestones && proposal.milestones.length > 0) {
    for (let i = 0; i < proposal.milestones.length; i++) {
      const m = proposal.milestones[i];
      const issueRes = await fetch(`https://api.github.com/repos/${repo.full_name}/issues`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: `Milestone ${i + 1}: ${m.title || 'TBD'}`,
          body: `## Milestone ${i + 1}\n\n**Description:** ${m.description || 'TBD'}\n\n**Target Date:** ${m.target_date || 'TBD'}\n\n**Deliverables:** ${m.deliverables || 'TBD'}\n\n**Budget:** $${m.budget_usd || 'TBD'}`,
          labels: ['milestone', 'grant-deliverable'],
        }),
      });
      if (issueRes.ok) {
        const issue = await issueRes.json();
        milestoneIssues.push({ milestone_index: i, issue_number: issue.number, issue_url: issue.html_url });
      }
    }
  }

  // Create labels for the repo
  const labels = [
    { name: 'milestone', color: '0075ca', description: 'Grant milestone deliverable' },
    { name: 'grant-deliverable', color: '008672', description: 'Required grant deliverable' },
    { name: 'ripple-review', color: 'd876e3', description: 'Pending Ripple review' },
    { name: 'budget', color: 'e4e669', description: 'Budget-related item' },
    { name: 'progress-report', color: 'f9d0c4', description: 'Progress reporting' },
  ];

  for (const label of labels) {
    await fetch(`https://api.github.com/repos/${repo.full_name}/labels`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(label),
    }).catch(() => {}); // Labels may already exist
  }

  // Update the GrantProposal entity with the repo URL
  const updatedMilestones = (proposal.milestones || []).map((m, i) => {
    const issue = milestoneIssues.find(mi => mi.milestone_index === i);
    return { ...m, github_issue_number: issue?.issue_number };
  });

  await base44.asServiceRole.entities.GrantProposal.update(grant_proposal_id, {
    github_repo_url: repo.html_url,
    github_repo_name: repo.full_name,
    milestones: updatedMilestones,
  });

  // If linked to an AIProject, update that too
  if (proposal.ai_project_id) {
    try {
      const project = await base44.asServiceRole.entities.AIProject.get(proposal.ai_project_id);
      if (project) {
        const existingTags = project.tags || [];
        await base44.asServiceRole.entities.AIProject.update(proposal.ai_project_id, {
          tags: [...new Set([...existingTags, 'ripple-grant', repoName])],
        });
      }
    } catch (e) {
      console.warn('Could not update linked AIProject:', e.message);
    }
  }

  return Response.json({
    success: true,
    repository: {
      name: repo.full_name,
      url: repo.html_url,
      clone_url: repo.clone_url,
      private: repo.private,
    },
    milestone_issues: milestoneIssues,
    message: `Repository "${repo.full_name}" created with grant proposal structure and ${milestoneIssues.length} milestone issues.`,
  });
});

// Helper to create a file in the repo
async function createFile(token, repoFullName, path, content, message) {
  const encoded = btoa(unescape(encodeURIComponent(content)));
  const res = await fetch(`https://api.github.com/repos/${repoFullName}/contents/${path}`, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message,
      content: encoded,
    }),
  });
  return res.ok;
}