import React from 'react';
import { Leaf, Zap, TrendingDown } from 'lucide-react';

export default function CarbonFootprintExplainer() {
  return (
    <div className="bg-gradient-to-br from-emerald-950/40 via-green-950/30 to-slate-950 border border-emerald-500/20 rounded-2xl p-5 space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center">
          <Leaf className="w-4 h-4 text-emerald-400" />
        </div>
        <div>
          <h3 className="text-white font-semibold text-sm">Carbon Footprint \u2014 What It Means</h3>
          <p className="text-emerald-300/50 text-[10px]">Understanding Kinetic Waste & Environmental Impact</p>
        </div>
      </div>

      {/* Explanation Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
        {/* What */}
        <div className="bg-white/5 border border-white/10 rounded-lg p-3 space-y-1.5">
          <p className="text-emerald-300 font-semibold flex items-center gap-1.5">
            <Zap className="w-3 h-3" /> What We Measure
          </p>
          <p className="text-white/60 leading-relaxed">
            CO\u2082e grams generated by stalled tasks, automation errors, inefficient production chains, and idle resources. Every digital action has an environmental cost.
          </p>
        </div>

        {/* Why */}
        <div className="bg-white/5 border border-white/10 rounded-lg p-3 space-y-1.5">
          <p className="text-emerald-300 font-semibold flex items-center gap-1.5">
            <TrendingDown className="w-3 h-3" /> Why It Matters
          </p>
          <p className="text-white/60 leading-relaxed">
            SoulBridge is a <strong>Living Republic</strong>, not a platform. Waste is death. Flow is life. We measure kinetic waste to eliminate it and align all actions with environmental stewardship.
          </p>
        </div>

        {/* How */}
        <div className="bg-white/5 border border-white/10 rounded-lg p-3 space-y-1.5 sm:col-span-2">
          <p className="text-emerald-300 font-semibold flex items-center gap-1.5">
            <Leaf className="w-3 h-3" /> How We Reduce It
          </p>
          <p className="text-white/60 leading-relaxed">
            By detecting bottlenecks, automating inefficiencies, reallocating idle resources, and celebrating progress. The chart shows daily snapshots\u2014when waste \u2193 and savings \u2191, we\u2019re flowing. When waste \u2191, we investigate and intervene.
          </p>
        </div>
      </div>

      {/* Chat Button */}
      <button
        onClick={() => window.dispatchEvent(new CustomEvent('open-axi-with-message', { detail: { initialMessage: 'Tell me about kinetic waste and carbon footprint in SoulBridge' } }))}
        className="w-full text-emerald-300 hover:text-emerald-200 text-xs font-semibold border border-emerald-500/30 hover:border-emerald-400/50 rounded-lg px-3 py-2 transition flex items-center justify-center gap-2\u201d"
      >
        Chat with Kinetic Weather AI \u2192
      </button>
    </div>
  );
}