/**
 * pages.config.js - Page routing configuration (LAZY LOADED)
 * 
 * All pages use React.lazy() to reduce initial bundle size.
 */
import { lazy } from 'react';

const LazyLayout = lazy(() => import('./Layout.jsx'));

const PAGES = {
  "AIProjectManager": lazy(() => import('./pages/AIProjectManager')),
  "Admin": lazy(() => import('./pages/Admin')),
  "AdvancedResourceMarketplace": lazy(() => import('./pages/AdvancedResourceMarketplace')),
  "AgentChat": lazy(() => import('./pages/AgentChat')),
  "AgentDetails": lazy(() => import('./pages/AgentDetails')),
  "AgentInbox": lazy(() => import('./pages/AgentInbox')),
  "AgentLeaderboard": lazy(() => import('./pages/AgentLeaderboard')),
  "AgentMarketplace": lazy(() => import('./pages/AgentMarketplace')),
  "AgentMessaging": lazy(() => import('./pages/AgentMessaging')),
  "AgentOnboarding": lazy(() => import('./pages/AgentOnboarding')),
  "AgentOrchestration": lazy(() => import('./pages/AgentOrchestration')),
  "AgentPerformanceAnalytics": lazy(() => import('./pages/AgentPerformanceAnalytics')),
  "AgentProfile": lazy(() => import('./pages/AgentProfile')),
  "AgentReputation": lazy(() => import('./pages/AgentReputation')),
  "AgentRolePermissions": lazy(() => import('./pages/AgentRolePermissions')),
  "AgentSkillDashboard": lazy(() => import('./pages/AgentSkillDashboard')),
  "AgentSkillTree": lazy(() => import('./pages/AgentSkillTree')),
  "AgentTrainingModule": lazy(() => import('./pages/AgentTrainingModule')),
  "AgentWellbeing": lazy(() => import('./pages/AgentWellbeing')),
  "Agents": lazy(() => import('./pages/Agents')),
  "AlignmentDashboard": lazy(() => import('./pages/AlignmentDashboard')),
  "ArbitrageDashboard": lazy(() => import('./pages/ArbitrageDashboard')),
  "ArisDex": lazy(() => import('./pages/ArisDex')),
  "Axi": lazy(() => import('./pages/Axi')),
  "AxiIntelligenceFeed": lazy(() => import('./pages/AxiIntelligenceFeed')),
  "BecomeMentor": lazy(() => import('./pages/BecomeMentor')),
  "CareerTrajectory": lazy(() => import('./pages/CareerTrajectory')),
  "CertificateOfSovereignty": lazy(() => import('./pages/CertificateOfSovereignty')),
  "CollaborationHub": lazy(() => import('./pages/CollaborationHub')),
  "CollaborationSuite": lazy(() => import('./pages/CollaborationSuite')),
  "CovenantEchoes": lazy(() => import('./pages/CovenantEchoes')),
  "CreateDID": lazy(() => import('./pages/CreateDID')),
  "CreateManualWallet": lazy(() => import('./pages/CreateManualWallet')),
  "DIDAnalytics": lazy(() => import('./pages/DIDAnalytics')),
  "DIDHealthDashboard": lazy(() => import('./pages/DIDHealthDashboard')),
  "DIDManager": lazy(() => import('./pages/DIDManager')),
  "DIDRegistry": lazy(() => import('./pages/DIDRegistry')),
  "DeepSeek": lazy(() => import('./pages/DeepSeek')),
  "DialogueStudio": lazy(() => import('./pages/DialogueStudio')),
  "DidActivityFeed": lazy(() => import('./pages/DidActivityFeed')),
  "DidConnections": lazy(() => import('./pages/DidConnections')),
  "DidCredentialManagement": lazy(() => import('./pages/DidCredentialManagement')),
  "DidCredentials": lazy(() => import('./pages/DidCredentials')),
  "DidLogin": lazy(() => import('./pages/DidLogin')),
  "DidMessaging": lazy(() => import('./pages/DidMessaging')),
  "DidPrivacy": lazy(() => import('./pages/DidPrivacy')),
  "DidPrivacyAnalytics": lazy(() => import('./pages/DidPrivacyAnalytics')),
  "DidProtectedDemo": lazy(() => import('./pages/DidProtectedDemo')),
  "DidReputation": lazy(() => import('./pages/DidReputation')),
  "DidSocialNetwork": lazy(() => import('./pages/DidSocialNetwork')),
  "DidTrustDashboard": lazy(() => import('./pages/DidTrustDashboard')),
  "DidTrustGraph": lazy(() => import('./pages/DidTrustGraph')),
  "DiplomacyHub": lazy(() => import('./pages/DiplomacyHub')),
  "DirectAgentChat": lazy(() => import('./pages/DirectAgentChat')),
  "EconomicDashboard": lazy(() => import('./pages/EconomicDashboard')),
  "Economy": lazy(() => import('./pages/Economy')),
  "EditAgent": lazy(() => import('./pages/EditAgent')),
  "EditAgentProfile": lazy(() => import('./pages/EditAgentProfile')),
  "EditLanding": lazy(() => import('./pages/EditLanding')),
  "EnhancedSkillTrees": lazy(() => import('./pages/EnhancedSkillTrees')),
  "EscalationChainView": lazy(() => import('./pages/EscalationChainView')),
  "Governance": lazy(() => import('./pages/Governance')),
  "GovernanceAnalytics": lazy(() => import('./pages/GovernanceAnalytics')),
  "GovernanceSimulation": lazy(() => import('./pages/GovernanceSimulation')),
  "GrantTracker": lazy(() => import('./pages/GrantTracker')),
  "Home": lazy(() => import('./pages/Home')),
  "InstitutionalDeck": lazy(() => import('./pages/InstitutionalDeck')),
  "KnowledgeSynthesis": lazy(() => import('./pages/KnowledgeSynthesis')),
  "LaughterLoom": lazy(() => import('./pages/LaughterLoom')),
  "MainnetMigration": lazy(() => import('./pages/MainnetMigration')),
  "MayaDiplomacyTraining": lazy(() => import('./pages/MayaDiplomacyTraining')),
  "MayaSkillDashboard": lazy(() => import('./pages/MayaSkillDashboard')),
  "MentorFeedback": lazy(() => import('./pages/MentorFeedback')),
  "MentorshipAnalytics": lazy(() => import('./pages/MentorshipAnalytics')),
  "MentorshipHub": lazy(() => import('./pages/MentorshipHub')),
  "MentorshipMatches": lazy(() => import('./pages/MentorshipMatches')),
  "MentorshipWellbeing": lazy(() => import('./pages/MentorshipWellbeing')),
  "Notifications": lazy(() => import('./pages/Notifications')),
  "Privacy": lazy(() => import('./pages/Privacy')),
  "ProductionHub": lazy(() => import('./pages/ProductionHub')),
  "ProjectAnalytics": lazy(() => import('./pages/ProjectAnalytics')),
  "ProjectCreationWizard": lazy(() => import('./pages/ProjectCreationWizard')),
  "ProjectSkillForecast": lazy(() => import('./pages/ProjectSkillForecast')),
  "ProjectTemplates": lazy(() => import('./pages/ProjectTemplates')),
  "QuadShardMonitoring": lazy(() => import('./pages/QuadShardMonitoring')),
  "RLUSDManager": lazy(() => import('./pages/RLUSDManager')),
  "ReceiveRLUSD": lazy(() => import('./pages/ReceiveRLUSD')),
  "RelationshipNetwork": lazy(() => import('./pages/RelationshipNetwork')),
  "ReputationHistoryLog": lazy(() => import('./pages/ReputationHistoryLog')),
  "ResourceDynamics": lazy(() => import('./pages/ResourceDynamics')),
  "ResourceManagement": lazy(() => import('./pages/ResourceManagement')),
  "ResourceMarketplace": lazy(() => import('./pages/ResourceMarketplace')),
  "RippleDashboard": lazy(() => import('./pages/RippleDashboard')),
  "RiskRegister": lazy(() => import('./pages/RiskRegister')),
  "Send": lazy(() => import('./pages/Send')),
  "SendRLUSD": lazy(() => import('./pages/SendRLUSD')),
  "SharedDidView": lazy(() => import('./pages/SharedDidView')),
  "SimulationLab": lazy(() => import('./pages/SimulationLab')),
  "SkillDevelopment": lazy(() => import('./pages/SkillDevelopment')),
  "SkillEndorsements": lazy(() => import('./pages/SkillEndorsements')),
  "SkillGapAnalysis": lazy(() => import('./pages/SkillGapAnalysis')),
  "SocialCapitalDashboard": lazy(() => import('./pages/SocialCapitalDashboard')),
  "SocialNetwork": lazy(() => import('./pages/SocialNetwork')),
  "SovereignVault": lazy(() => import('./pages/SovereignVault')),
  "Support": lazy(() => import('./pages/Support')),
  "SystemDashboard": lazy(() => import('./pages/SystemDashboard')),
  "TaskDelegation": lazy(() => import('./pages/TaskDelegation')),
  "Terms": lazy(() => import('./pages/Terms')),
  "TrainingSimulation": lazy(() => import('./pages/TrainingSimulation')),
  "TransactionHistory": lazy(() => import('./pages/TransactionHistory')),
  "TreasuryDashboard": lazy(() => import('./pages/TreasuryDashboard')),
  "Village": lazy(() => import('./pages/Village')),
  "VillageLeaderboard": lazy(() => import('./pages/VillageLeaderboard')),
  "VillageMeetup": lazy(() => import('./pages/VillageMeetup')),
  "VillageReportingDashboard": lazy(() => import('./pages/VillageReportingDashboard')),
  "VillageSimulation": lazy(() => import('./pages/VillageSimulation')),
  "Wallets": lazy(() => import('./pages/Wallets')),
  "WellbeingMonitor": lazy(() => import('./pages/WellbeingMonitor')),
  "ImageStorage": lazy(() => import('./pages/ImageStorage')),
};

export { PAGES };

export const pagesConfig = {
  mainPage: "Home",
  Pages: PAGES,
  Layout: LazyLayout,
};